server {
    listen 80;
    server_name adv-an.tsaone.cloud;

    root /opt/adscore;

    location /static/ {
        alias /opt/adscore/static/;
        expires 30d;
    }

    location /uploads/ {
        alias /opt/adscore/uploads/;
        expires 7d;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn-adscore.sock;
    }

    client_max_body_size 20M;
}
